#!/usr/bin/env python3
""" Factor numbers """
from sys import argv

def open_read_file(file_name):
    """ Read from file and add to an array """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    numbers_to_factor = []
    for line in lines:
        numbers_to_factor.append(int(line))
    return numbers_to_factor

def find_and_times(n):
    """ Factor the given number """
    for i in range(2, n + 1):
        while n % i == 0:
            n //= i
            print(f"{n * i}={n}*{i}")
        if n == 1:
            break

def factorize_list(numbers):
    """ Factorize each number in the list """
    for num in numbers:
        find_and_times(num)

if len(argv) == 2:
    factorize_list(open_read_file(argv[1]))
