#!/usr/bin/python3
from sys import argv

def factorize(num):
    factors = []
    
    while num % 2 == 0:
        factors.append(2)
        num //= 2
    
    for i in range(3, int(num**0.5) + 1, 2):
        while num % i == 0:
            factors.append(i)
            num //= i
    
    if num > 1:
        factors.append(num)
    
    return factors

if len(argv) == 2:
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            factors = factorize(num)
            print(f"{num}={'*'.join(map(str, factors))}")
