#!/usr/bin/env python3
from sys import argv

def factorize(n):
    for i in range(2, n):
        if n % i == 0:
            p = i
            q = n // i
            return p, q

if len(argv) == 2:
    n = int(argv[1])
    p, q = factorize(n)
    print(f"{n}={p}*{q}")
