#!/usr/bin/python3
from sys import argv

def factorize(num):
    factors = []
    
    # Handle factors of 2
    while num % 2 == 0:
        factors.append(2)
        num //= 2
    
    # Handle remaining prime factors
    div = 3
    while div * div <= num:
        while num % div == 0:
            factors.append(div)
            num //= div
        div += 2  # Skip even divisors
    
    # If num is still greater than 1, it's a prime factor
    if num > 1:
        factors.append(num)
    
    return factors

if len(argv) == 2:
    with open(argv[1]) as f:
        for line in f:
            num = int(line)
            factors = factorize(num)
            print(f"{num}={'*'.join(map(str, factors))}")
